using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using CompanyRecommanderSystem.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace CompanyRecommanderSystem.Controllers
{
    [ApiController]
    [Produces("application/json")]
    [Route("[controller]")]
    public class SearchController : ControllerBase
    {
        [HttpPost]
        public bool Search([FromBody] SearchInput searchInput)
        {
            /*string filePythonExePath = "C:\\Users\\yosri\\Downloads\\python-3.8.5.exe";
            string filePythonNamePath = "";
            var filePythonInput = searchInput;
            string outputText, standardError;
            IMLSharpPython mlSharpPython = new MLSharpPython(filePythonExePath);
            string fileNameParameter = $"{filePythonNamePath} {"test"} {"imagePathName"}";
            outputText = mlSharpPython.ExecutePythonScript(fileNameParameter, out standardError);
            if (string.IsNullOrEmpty(standardError))
            {
                switch (outputText.ToLower())
                {
                    case "1":
                        Console.WriteLine("Image category 1");
                        break;
                    case "0":
                        Console.WriteLine("Image category 0");
                        break;
                    default:
                        Console.WriteLine(outputText);
                        break;
                }
            }
            else
            {
                Console.WriteLine(standardError);
            }
            Console.ReadKey();*/
            System.Diagnostics.ProcessStartInfo start = new System.Diagnostics.ProcessStartInfo();
            //python interprater location
            start.FileName = @"C:\Users\yosri\AppData\Local\Programs\Python\Python38-32\python.exe";
            //argument with file name and input parameters
            start.Arguments = string.Format("{0} {1}", @"C:\Users\yosri\Desktop\PythonSampleSystemDiagnostic.py", JsonConvert.SerializeObject(searchInput));
            start.UseShellExecute = false;// Do not use OS shell
            start.CreateNoWindow = true; // We don't need new window
            start.RedirectStandardOutput = true;// Any output, generated by application will be redirected back
            start.RedirectStandardError = true; // Any error in standard output will be redirected back (for example exceptions)
            start.LoadUserProfile = true;
            using (System.Diagnostics.Process process = System.Diagnostics.Process.Start(start))
            {
                using (StreamReader reader = process.StandardOutput)
                {
                    string stderr = process.StandardError.ReadToEnd(); // Here are the exceptions from our Python script
                    string result = reader.ReadToEnd(); // Here is the result of StdOut(for example: print "test")
                    Console.WriteLine("From System Diagnostics");
                    Console.WriteLine("5 + 10 = {0}", result);
                }
            }

            Console.ReadLine();
            return true;
        }
    }
}
