using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace CompanyRecommanderSystem.Models
{
    public class AllCategories
    {
        public static List<Category> Categories = new List<Category>()
        {
            new Category(){ ParentCategory = "Administrative Services", ChildCategory = "Archiving Service" },
            new Category(){ ParentCategory = "Administrative Services", ChildCategory = "Call Center" },
            new Category(){ ParentCategory = "Administrative Services", ChildCategory = "Collection Agency" },
            new Category(){ ParentCategory = "Administrative Services", ChildCategory = "College Recruiting" },
            new Category(){ ParentCategory = "Administrative Services", ChildCategory = "Courier Service" },
            new Category(){ ParentCategory = "Administrative Services", ChildCategory = "Debt Collections" },
            new Category(){ ParentCategory = "Administrative Services", ChildCategory = "Delivery" },
            new Category(){ ParentCategory = "Administrative Services", ChildCategory = "Document Preparation" },
            new Category(){ ParentCategory = "Administrative Services", ChildCategory = "Extermination Service" },
            new Category(){ ParentCategory = "Administrative Services", ChildCategory = "Facilities Support Services" },
            new Category(){ ParentCategory = "Administrative Services", ChildCategory = "Housekeeping Service" },
            new Category(){ ParentCategory = "Administrative Services", ChildCategory = "Housekeeping Service" },
            new Category(){ ParentCategory = "Administrative Services", ChildCategory = "Office Administration" },
            new Category(){ ParentCategory = "Administrative Services", ChildCategory = "Packaging Services" },
            new Category(){ ParentCategory = "Administrative Services", ChildCategory = "Physical Security" },
            new Category(){ ParentCategory = "Administrative Services", ChildCategory = "Staffing Agency" },
            new Category(){ ParentCategory = "Administrative Services", ChildCategory = "Trade Shows" },
            new Category(){ ParentCategory = "Administrative Services", ChildCategory = "Virtual Workforce" },
            new Category(){ ParentCategory = "Advertising", ChildCategory = "Ad Exchange" },
            new Category(){ ParentCategory = "Advertising", ChildCategory = "Ad Network" },
            new Category(){ ParentCategory = "Advertising", ChildCategory = "Ad Retargeting" },
            new Category(){ ParentCategory = "Advertising", ChildCategory = "Ad Server" },
            new Category(){ ParentCategory = "Advertising", ChildCategory = "Ad Targeting" },
            new Category(){ ParentCategory = "Advertising", ChildCategory = "Advertising" },
            new Category(){ ParentCategory = "Advertising", ChildCategory = "Advertising Platforms" },
            new Category(){ ParentCategory = "Advertising", ChildCategory = "Affiliate Marketing" },
            new Category(){ ParentCategory = "Advertising", ChildCategory = "Local Advertising" },
            new Category(){ ParentCategory = "Advertising", ChildCategory = "Mobile Advertising" },
            new Category(){ ParentCategory = "Advertising", ChildCategory = "Outdoor Advertising" },
            new Category(){ ParentCategory = "Advertising", ChildCategory = "SEM" },
            new Category(){ ParentCategory = "Advertising", ChildCategory = "Social Media Advertising" },
            new Category(){ ParentCategory = "Advertising", ChildCategory = "Video Advertising" },
            new Category(){ ParentCategory = "Agriculture and Farming", ChildCategory = "Agriculture" },
            new Category(){ ParentCategory = "Agriculture and Farming", ChildCategory = "AgTech" },
            new Category(){ ParentCategory = "Agriculture and Farming", ChildCategory = "Animal Feed" },
            new Category(){ ParentCategory = "Agriculture and Farming", ChildCategory = "Aquaculture" },
            new Category(){ ParentCategory = "Agriculture and Farming", ChildCategory = "Equestrian" },
            new Category(){ ParentCategory = "Agriculture and Farming", ChildCategory = "Farming" },
            new Category(){ ParentCategory = "Agriculture and Farming", ChildCategory = "Forestry" },
            new Category(){ ParentCategory = "Agriculture and Farming", ChildCategory = "Horticulture" },
            new Category(){ ParentCategory = "Agriculture and Farming", ChildCategory = "Hydroponics" },
            new Category(){ ParentCategory = "Agriculture and Farming", ChildCategory = "Livestock" },
            new Category(){ ParentCategory = "Apps", ChildCategory = "App Discovery" },
            new Category(){ ParentCategory = "Apps", ChildCategory = "Apps" },
            new Category(){ ParentCategory = "Apps", ChildCategory = "Consumer Applications" },
            new Category(){ ParentCategory = "Apps", ChildCategory = "Enterprise Applications" },
            new Category(){ ParentCategory = "Apps", ChildCategory = "Mobile Apps" },
            new Category(){ ParentCategory = "Apps", ChildCategory = "Reading Apps" },
            new Category(){ ParentCategory = "Apps", ChildCategory = "Web Apps" },
            new Category(){ ParentCategory = "Artificial Intelligence", ChildCategory = "Artificial Intelligence" },
            new Category(){ ParentCategory = "Artificial Intelligence", ChildCategory = "Intelligent Systems" },
            new Category(){ ParentCategory = "Artificial Intelligence", ChildCategory = "Machine Learning" },
            new Category(){ ParentCategory = "Artificial Intelligence", ChildCategory = "Natural Language Processing" },
            new Category(){ ParentCategory = "Artificial Intelligence", ChildCategory = "Predictive Analytics" },
            new Category(){ ParentCategory = "Biotechnology", ChildCategory = "Bioinformatics" },
            new Category(){ ParentCategory = "Biotechnology", ChildCategory = "Biometrics" },
            new Category(){ ParentCategory = "Biotechnology", ChildCategory = "Biopharma" },
            new Category(){ ParentCategory = "Biotechnology", ChildCategory = "Biotechnology" },
            new Category(){ ParentCategory = "Biotechnology", ChildCategory = "Genetics" },
            new Category(){ ParentCategory = "Biotechnology", ChildCategory = "Life Science" },
            new Category(){ ParentCategory = "Biotechnology", ChildCategory = "Neuroscience" },
            new Category(){ ParentCategory = "Biotechnology", ChildCategory = "Quantified Self" },
            new Category(){ ParentCategory = "Clothing and Apparel", ChildCategory = "Fashion" },
            new Category(){ ParentCategory = "Clothing and Apparel", ChildCategory = "Laundry and Dry-cleaning" },
            new Category(){ ParentCategory = "Clothing and Apparel", ChildCategory = "Lingerie" },
            new Category(){ ParentCategory = "Clothing and Apparel", ChildCategory = "Shoes" },
            new Category(){ ParentCategory = "Commerce and Shopping", ChildCategory = "Auctions" },
            new Category(){ ParentCategory = "Commerce and Shopping", ChildCategory = "Classifieds" },
            new Category(){ ParentCategory = "Commerce and Shopping", ChildCategory = "Collectibles" },
            new Category(){ ParentCategory = "Commerce and Shopping", ChildCategory = "Consumer Reviews" },
            new Category(){ ParentCategory = "Commerce and Shopping", ChildCategory = "Coupons" },
            new Category(){ ParentCategory = "Commerce and Shopping", ChildCategory = "E-Commerce" },
            new Category(){ ParentCategory = "Commerce and Shopping", ChildCategory = "E-Commerce Platforms" },
            new Category(){ ParentCategory = "Commerce and Shopping", ChildCategory = "Flash Sale" },
            new Category(){ ParentCategory = "Commerce and Shopping", ChildCategory = "Gift" },
            new Category(){ ParentCategory = "Commerce and Shopping", ChildCategory = "Gift Card" },
            new Category(){ ParentCategory = "Commerce and Shopping", ChildCategory = "Gift Exchange" },
            new Category(){ ParentCategory = "Commerce and Shopping", ChildCategory = "Group Buying" },
            new Category(){ ParentCategory = "Commerce and Shopping", ChildCategory = "Local Shopping" },
            new Category(){ ParentCategory = "Commerce and Shopping", ChildCategory = "Made to Order" },
            new Category(){ ParentCategory = "Commerce and Shopping", ChildCategory = "Marketplace" },
            new Category(){ ParentCategory = "Commerce and Shopping", ChildCategory = "Online Auctions" },
            new Category(){ ParentCategory = "Commerce and Shopping", ChildCategory = "Point of Sale" },
            new Category(){ ParentCategory = "Commerce and Shopping", ChildCategory = "Price Comparison" },
            new Category(){ ParentCategory = "Commerce and Shopping", ChildCategory = "Rental" },
            new Category(){ ParentCategory = "Commerce and Shopping", ChildCategory = "Retail" },
            new Category(){ ParentCategory = "Commerce and Shopping", ChildCategory = "Retail Technology" },
            new Category(){ ParentCategory = "Commerce and Shopping", ChildCategory = "Shopping" },
            new Category(){ ParentCategory = "Commerce and Shopping", ChildCategory = "Shopping Mall" },
            new Category(){ ParentCategory = "Commerce and Shopping", ChildCategory = "Social Shopping" },
            new Category(){ ParentCategory = "Commerce and Shopping", ChildCategory = "Sporting Goods" },
            new Category(){ ParentCategory = "Commerce and Shopping", ChildCategory = "Vending and Concessions" },
            new Category(){ ParentCategory = "Commerce and Shopping", ChildCategory = "Virtual Goods" },
            new Category(){ ParentCategory = "Commerce and Shopping", ChildCategory = "Wholesale" },
            new Category(){ ParentCategory = "Community and Lifestyle", ChildCategory = "Cannabis" },
            new Category(){ ParentCategory = "Community and Lifestyle", ChildCategory = "Communities" },
            new Category(){ ParentCategory = "Community and Lifestyle", ChildCategory = "Dating" },
            new Category(){ ParentCategory = "Community and Lifestyle", ChildCategory = "Humanitarian" },
            new Category(){ ParentCategory = "Community and Lifestyle", ChildCategory = "Leisure" },
            new Category(){ ParentCategory = "Community and Lifestyle", ChildCategory = "Lifestyle" },
            new Category(){ ParentCategory = "Community and Lifestyle", ChildCategory = "Online Forums" },
            new Category(){ ParentCategory = "Community and Lifestyle", ChildCategory = "Parenting" },
            new Category(){ ParentCategory = "Community and Lifestyle", ChildCategory = "Pet" },
            new Category(){ ParentCategory = "Community and Lifestyle", ChildCategory = "Private Social Networking" },
            new Category(){ ParentCategory = "Community and Lifestyle", ChildCategory = "Professional Networking" },
            new Category(){ ParentCategory = "Community and Lifestyle", ChildCategory = "Q&A" },
            new Category(){ ParentCategory = "Community and Lifestyle", ChildCategory = "Religion" },
            new Category(){ ParentCategory = "Community and Lifestyle", ChildCategory = "Sex Industry" },
            new Category(){ ParentCategory = "Community and Lifestyle", ChildCategory = "Social Entrepreneurship" },
            new Category(){ ParentCategory = "Community and Lifestyle", ChildCategory = "Virtual World" },
            new Category(){ ParentCategory = "Community and Lifestyle", ChildCategory = "Wedding" },
            new Category(){ ParentCategory = "Consumer Electronics", ChildCategory = "Computer" },
            new Category(){ ParentCategory = "Consumer Electronics", ChildCategory = "Consumer Electronics" },
            new Category(){ ParentCategory = "Consumer Electronics", ChildCategory = "Drones" },
            new Category(){ ParentCategory = "Consumer Electronics", ChildCategory = "Electronics" },
            new Category(){ ParentCategory = "Consumer Electronics", ChildCategory = "Google Glass" },
            new Category(){ ParentCategory = "Consumer Electronics", ChildCategory = "Mobile Devices" },
            new Category(){ ParentCategory = "Consumer Electronics", ChildCategory = "Nintendo" },
            new Category(){ ParentCategory = "Consumer Electronics", ChildCategory = "Playstation" },
            new Category(){ ParentCategory = "Consumer Electronics", ChildCategory = "Roku" },
            new Category(){ ParentCategory = "Consumer Electronics", ChildCategory = "Smart Home" },
            new Category(){ ParentCategory = "Consumer Electronics", ChildCategory = "Wearables" },
            new Category(){ ParentCategory = "Consumer Electronics", ChildCategory = "Windows Phone" },
            new Category(){ ParentCategory = "Consumer Electronics", ChildCategory = "Xbox" },
            new Category(){ ParentCategory = "Consumer Goods", ChildCategory = "Beauty" },
            new Category(){ ParentCategory = "Consumer Goods", ChildCategory = "Comics" },
            new Category(){ ParentCategory = "Consumer Goods", ChildCategory = "Consumer Goods" },
            new Category(){ ParentCategory = "Consumer Goods", ChildCategory = "Cosmetics" },
            new Category(){ ParentCategory = "Consumer Goods", ChildCategory = "DIY" },
            new Category(){ ParentCategory = "Consumer Goods", ChildCategory = "Drones" },
            new Category(){ ParentCategory = "Consumer Goods", ChildCategory = "Eyewear" },
            new Category(){ ParentCategory = "Consumer Goods", ChildCategory = "Fast-Moving Consumer Goods" },
            new Category(){ ParentCategory = "Consumer Goods", ChildCategory = "Flowers" },
            new Category(){ ParentCategory = "Consumer Goods", ChildCategory = "Furniture" },
            new Category(){ ParentCategory = "Consumer Goods", ChildCategory = "Green Consumer Goods" },
            new Category(){ ParentCategory = "Consumer Goods", ChildCategory = "Jewelry" },
            new Category(){ ParentCategory = "Consumer Goods", ChildCategory = "Lingerie" },
            new Category(){ ParentCategory = "Consumer Goods", ChildCategory = "Shoes" },
            new Category(){ ParentCategory = "Consumer Goods", ChildCategory = "Tobacco" },
            new Category(){ ParentCategory = "Consumer Goods", ChildCategory = "Toys" },
            new Category(){ ParentCategory = "Content and Publishing", ChildCategory = "Blogging Platforms" },
            new Category(){ ParentCategory = "Content and Publishing", ChildCategory = "Content Delivery Network" },
            new Category(){ ParentCategory = "Content and Publishing", ChildCategory = "Content Discovery" },
            new Category(){ ParentCategory = "Content and Publishing", ChildCategory = "Content Syndication" },
            new Category(){ ParentCategory = "Content and Publishing", ChildCategory = "Creative Agency" },
            new Category(){ ParentCategory = "Content and Publishing", ChildCategory = "DRM" },
            new Category(){ ParentCategory = "Content and Publishing", ChildCategory = "EBooks" },
            new Category(){ ParentCategory = "Content and Publishing", ChildCategory = "Journalism" },
            new Category(){ ParentCategory = "Content and Publishing", ChildCategory = "News" },
            new Category(){ ParentCategory = "Content and Publishing", ChildCategory = "Photo Editing" },
            new Category(){ ParentCategory = "Content and Publishing", ChildCategory = "Photo Sharing" },
            new Category(){ ParentCategory = "Content and Publishing", ChildCategory = "Photography" },
            new Category(){ ParentCategory = "Content and Publishing", ChildCategory = "Printing" },
            new Category(){ ParentCategory = "Content and Publishing", ChildCategory = "Publishing" },
            new Category(){ ParentCategory = "Content and Publishing", ChildCategory = "Video Editing" },
            new Category(){ ParentCategory = "Content and Publishing", ChildCategory = "Video Streaming" },
            new Category(){ ParentCategory = "Data and Analytics", ChildCategory = "A/B Testing" },
            new Category(){ ParentCategory = "Data and Analytics", ChildCategory = "Analytics" },
            new Category(){ ParentCategory = "Data and Analytics", ChildCategory = "Application Performance Management" },
            new Category(){ ParentCategory = "Data and Analytics", ChildCategory = "Artificial Intelligence" },
            new Category(){ ParentCategory = "Data and Analytics", ChildCategory = "Big Data" },
            new Category(){ ParentCategory = "Data and Analytics", ChildCategory = "Bioinformatics" },
            new Category(){ ParentCategory = "Data and Analytics", ChildCategory = "Biometrics" },
            new Category(){ ParentCategory = "Data and Analytics", ChildCategory = "Business Intelligence" },
            new Category(){ ParentCategory = "Data and Analytics", ChildCategory = "Consumer Research" },
            new Category(){ ParentCategory = "Data and Analytics", ChildCategory = "Data Integration" },
            new Category(){ ParentCategory = "Data and Analytics", ChildCategory = "Data Mining" },
            new Category(){ ParentCategory = "Data and Analytics", ChildCategory = "Data Visualization" },
            new Category(){ ParentCategory = "Data and Analytics", ChildCategory = "Database" },
            new Category(){ ParentCategory = "Data and Analytics", ChildCategory = "Facial Recognition" },
            new Category(){ ParentCategory = "Data and Analytics", ChildCategory = "Geospatial" },
            new Category(){ ParentCategory = "Data and Analytics", ChildCategory = "Image Recognition" },
            new Category(){ ParentCategory = "Data and Analytics", ChildCategory = "Intelligent Systems" },
            new Category(){ ParentCategory = "Data and Analytics", ChildCategory = "Location Based Services" },
            new Category(){ ParentCategory = "Data and Analytics", ChildCategory = "Machine Learning" },
            new Category(){ ParentCategory = "Data and Analytics", ChildCategory = "Market Research" },
            new Category(){ ParentCategory = "Data and Analytics", ChildCategory = "Natural Language Processing" },
            new Category(){ ParentCategory = "Data and Analytics", ChildCategory = "Predictive Analytics" },
            new Category(){ ParentCategory = "Data and Analytics", ChildCategory = "Product Research" },
            new Category(){ ParentCategory = "Data and Analytics", ChildCategory = "Quantified Self" },
            new Category(){ ParentCategory = "Data and Analytics", ChildCategory = "Speech Recognition" },
            new Category(){ ParentCategory = "Data and Analytics", ChildCategory = "Test and Measurement" },
            new Category(){ ParentCategory = "Data and Analytics", ChildCategory = "Text Analytics" },
            new Category(){ ParentCategory = "Data and Analytics", ChildCategory = "Usability Testing" },
            new Category(){ ParentCategory = "Design", ChildCategory = "CAD" },
            new Category(){ ParentCategory = "Design", ChildCategory = "Consumer Research" },
            new Category(){ ParentCategory = "Design", ChildCategory = "Data Visualization" },
            new Category(){ ParentCategory = "Design", ChildCategory = "Fashion" },
            new Category(){ ParentCategory = "Design", ChildCategory = "Graphic Design" },
            new Category(){ ParentCategory = "Design", ChildCategory = "Human Computer Interaction" },
            new Category(){ ParentCategory = "Design", ChildCategory = "Industrial Design" },
            new Category(){ ParentCategory = "Design", ChildCategory = "Interior Design" },
            new Category(){ ParentCategory = "Design", ChildCategory = "Market Research" },
            new Category(){ ParentCategory = "Design", ChildCategory = "Mechanical Design" },
            new Category(){ ParentCategory = "Design", ChildCategory = "Product Design" },
            new Category(){ ParentCategory = "Design", ChildCategory = "Product Research" },
            new Category(){ ParentCategory = "Design", ChildCategory = "Usability Testing" },
            new Category(){ ParentCategory = "Design", ChildCategory = "UX Design" },
            new Category(){ ParentCategory = "Design", ChildCategory = "Web Design" },
            new Category(){ ParentCategory = "Education", ChildCategory = "Charter Schools" },
            new Category(){ ParentCategory = "Education", ChildCategory = "College Recruiting" },
            new Category(){ ParentCategory = "Education", ChildCategory = "Continuing Education" },
            new Category(){ ParentCategory = "Education", ChildCategory = "Corporate Training" },
            new Category(){ ParentCategory = "Education", ChildCategory = "E-Learning" },
            new Category(){ ParentCategory = "Education", ChildCategory = "EdTech" },
            new Category(){ ParentCategory = "Education", ChildCategory = "Education" },
            new Category(){ ParentCategory = "Education", ChildCategory = "Edutainment" },
            new Category(){ ParentCategory = "Education", ChildCategory = "Higher Education" },
            new Category(){ ParentCategory = "Education", ChildCategory = "Language Learning" },
            new Category(){ ParentCategory = "Education", ChildCategory = "MOOC" },
            new Category(){ ParentCategory = "Education", ChildCategory = "Music Education" },
            new Category(){ ParentCategory = "Education", ChildCategory = "Personal Development" },
            new Category(){ ParentCategory = "Education", ChildCategory = "Primary Education" },
            new Category(){ ParentCategory = "Education", ChildCategory = "Secondary Education" },
            new Category(){ ParentCategory = "Education", ChildCategory = "Skill Assessment" },
            new Category(){ ParentCategory = "Education", ChildCategory = "STEM Education" },
            new Category(){ ParentCategory = "Education", ChildCategory = "Textbook" },
            new Category(){ ParentCategory = "Education", ChildCategory = "Training" },
            new Category(){ ParentCategory = "Education", ChildCategory = "Tutoring" },
            new Category(){ ParentCategory = "Education", ChildCategory = "Vocational Education" },
            new Category(){ ParentCategory = "Energy", ChildCategory = "Battery" },
            new Category(){ ParentCategory = "Energy", ChildCategory = "Biofuel" },
            new Category(){ ParentCategory = "Energy", ChildCategory = "Biomass Energy" },
            new Category(){ ParentCategory = "Energy", ChildCategory = "Clean Energy" },
            new Category(){ ParentCategory = "Energy", ChildCategory = "Electrical Distribution" },
            new Category(){ ParentCategory = "Energy", ChildCategory = "Energy" },
            new Category(){ ParentCategory = "Energy", ChildCategory = "Energy Efficiency" },
            new Category(){ ParentCategory = "Energy", ChildCategory = "Energy Management" },
            new Category(){ ParentCategory = "Energy", ChildCategory = "Energy Storage" },
            new Category(){ ParentCategory = "Energy", ChildCategory = "Fossil Fuels" },
            new Category(){ ParentCategory = "Energy", ChildCategory = "Fuel" },
            new Category(){ ParentCategory = "Energy", ChildCategory = "Fuel Cell" },
            new Category(){ ParentCategory = "Energy", ChildCategory = "Oil and Gas" },
            new Category(){ ParentCategory = "Energy", ChildCategory = "Power Grid" },
            new Category(){ ParentCategory = "Energy", ChildCategory = "Renewable Energy" },
            new Category(){ ParentCategory = "Energy", ChildCategory = "Solar" },
            new Category(){ ParentCategory = "Energy", ChildCategory = "Wind Energy" },
            new Category(){ ParentCategory = "Events", ChildCategory = "Concerts" },
            new Category(){ ParentCategory = "Events", ChildCategory = "Event Management" },
            new Category(){ ParentCategory = "Events", ChildCategory = "Event Promotion" },
            new Category(){ ParentCategory = "Events", ChildCategory = "Events" },
            new Category(){ ParentCategory = "Events", ChildCategory = "Nightclubs" },
            new Category(){ ParentCategory = "Events", ChildCategory = "Nightlife" },
            new Category(){ ParentCategory = "Events", ChildCategory = "Reservations" },
            new Category(){ ParentCategory = "Events", ChildCategory = "Ticketing" },
            new Category(){ ParentCategory = "Events", ChildCategory = "Wedding" },
            new Category(){ ParentCategory = "Financial Services", ChildCategory = "Accounting" },
            new Category(){ ParentCategory = "Financial Services", ChildCategory = "Angel Investment" },
            new Category(){ ParentCategory = "Financial Services", ChildCategory = "Asset Management" },
            new Category(){ ParentCategory = "Financial Services", ChildCategory = "Auto Insurance" },
            new Category(){ ParentCategory = "Financial Services", ChildCategory = "Banking" },
            new Category(){ ParentCategory = "Financial Services", ChildCategory = "Bitcoin" },
            new Category(){ ParentCategory = "Financial Services", ChildCategory = "Commercial Insurance" },
            new Category(){ ParentCategory = "Financial Services", ChildCategory = "Commercial Lending" },
            new Category(){ ParentCategory = "Financial Services", ChildCategory = "Consumer Lending" },
            new Category(){ ParentCategory = "Financial Services", ChildCategory = "Credit" },
            new Category(){ ParentCategory = "Financial Services", ChildCategory = "Credit Bureau" },
            new Category(){ ParentCategory = "Financial Services", ChildCategory = "Credit Cards" },
            new Category(){ ParentCategory = "Financial Services", ChildCategory = "Crowdfunding" },
            new Category(){ ParentCategory = "Financial Services", ChildCategory = "Cryptocurrency" },
            new Category(){ ParentCategory = "Financial Services", ChildCategory = "Debit Cards" },
            new Category(){ ParentCategory = "Financial Services", ChildCategory = "Debt Collections" },
            new Category(){ ParentCategory = "Financial Services", ChildCategory = "Finance" },
            new Category(){ ParentCategory = "Financial Services", ChildCategory = "Financial Exchanges" },
            new Category(){ ParentCategory = "Financial Services", ChildCategory = "Financial Services" },
            new Category(){ ParentCategory = "Financial Services", ChildCategory = "FinTech" },
            new Category(){ ParentCategory = "Financial Services", ChildCategory = "Fraud Detection" },
            new Category(){ ParentCategory = "Financial Services", ChildCategory = "Funding Platform" },
            new Category(){ ParentCategory = "Financial Services", ChildCategory = "Gift Card" },
            new Category(){ ParentCategory = "Financial Services", ChildCategory = "Health Insurance" },
            new Category(){ ParentCategory = "Financial Services", ChildCategory = "Hedge Funds" },
            new Category(){ ParentCategory = "Financial Services", ChildCategory = "Impact Investing" },
            new Category(){ ParentCategory = "Financial Services", ChildCategory = "Incubators" },
            new Category(){ ParentCategory = "Financial Services", ChildCategory = "Insurance" },
            new Category(){ ParentCategory = "Financial Services", ChildCategory = "InsurTech" },
            new Category(){ ParentCategory = "Financial Services", ChildCategory = "Leasing" },
            new Category(){ ParentCategory = "Financial Services", ChildCategory = "Lending" },
            new Category(){ ParentCategory = "Financial Services", ChildCategory = "Life Insurance" },
            new Category(){ ParentCategory = "Financial Services", ChildCategory = "Micro Lending" },
            new Category(){ ParentCategory = "Financial Services", ChildCategory = "Mobile Payments" },
            new Category(){ ParentCategory = "Financial Services", ChildCategory = "Payments" },
            new Category(){ ParentCategory = "Financial Services", ChildCategory = "Personal Finance" },
            new Category(){ ParentCategory = "Financial Services", ChildCategory = "Prediction Markets" },
            new Category(){ ParentCategory = "Financial Services", ChildCategory = "Property Insurance" },
            new Category(){ ParentCategory = "Financial Services", ChildCategory = "Real Estate Investment" },
            new Category(){ ParentCategory = "Financial Services", ChildCategory = "Stock Exchanges" },
            new Category(){ ParentCategory = "Financial Services", ChildCategory = "Trading Platform" },
            new Category(){ ParentCategory = "Financial Services", ChildCategory = "Transaction Processing" },
            new Category(){ ParentCategory = "Financial Services", ChildCategory = "Venture Capital" },
            new Category(){ ParentCategory = "Financial Services", ChildCategory = "Virtual Currency" },
            new Category(){ ParentCategory = "Financial Services", ChildCategory = "Wealth Management" },
            new Category(){ ParentCategory = "Food and Beverage", ChildCategory = "Bakery" },
            new Category(){ ParentCategory = "Food and Beverage", ChildCategory = "Brewing" },
            new Category(){ ParentCategory = "Food and Beverage", ChildCategory = "Cannabis" },
            new Category(){ ParentCategory = "Food and Beverage", ChildCategory = "Catering" },
            new Category(){ ParentCategory = "Food and Beverage", ChildCategory = "Coffee" },
            new Category(){ ParentCategory = "Food and Beverage", ChildCategory = "Confectionery" },
            new Category(){ ParentCategory = "Food and Beverage", ChildCategory = "Cooking" },
            new Category(){ ParentCategory = "Food and Beverage", ChildCategory = "Craft Beer" },
            new Category(){ ParentCategory = "Food and Beverage", ChildCategory = "Dietary Supplements" },
            new Category(){ ParentCategory = "Food and Beverage", ChildCategory = "Distillery" },
            new Category(){ ParentCategory = "Food and Beverage", ChildCategory = "Farmers Market" },
            new Category(){ ParentCategory = "Food and Beverage", ChildCategory = "Food and Beverage" },
            new Category(){ ParentCategory = "Food and Beverage", ChildCategory = "Food Delivery" },
            new Category(){ ParentCategory = "Food and Beverage", ChildCategory = "Food Processing" },
            new Category(){ ParentCategory = "Food and Beverage", ChildCategory = "Food Trucks" },
            new Category(){ ParentCategory = "Food and Beverage", ChildCategory = "Fruit" },
            new Category(){ ParentCategory = "Food and Beverage", ChildCategory = "Grocery" },
            new Category(){ ParentCategory = "Food and Beverage", ChildCategory = "Nutrition" },
            new Category(){ ParentCategory = "Food and Beverage", ChildCategory = "Organic Food" },
            new Category(){ ParentCategory = "Food and Beverage", ChildCategory = "Recipes" },
            new Category(){ ParentCategory = "Food and Beverage", ChildCategory = "Restaurants" },
            new Category(){ ParentCategory = "Food and Beverage", ChildCategory = "Seafood" },
            new Category(){ ParentCategory = "Food and Beverage", ChildCategory = "Snack Food" },
            new Category(){ ParentCategory = "Food and Beverage", ChildCategory = "Tea" },
            new Category(){ ParentCategory = "Food and Beverage", ChildCategory = "Tobacco" },  
            new Category(){ ParentCategory = "Food and Beverage", ChildCategory = "Wine And Spirits" },  
            new Category(){ ParentCategory = "Food and Beverage", ChildCategory = "Winery" },  
            new Category(){ ParentCategory = "Gaming", ChildCategory = "Casual Games" },  
            new Category(){ ParentCategory = "Gaming", ChildCategory = "Console Games" },  
            new Category(){ ParentCategory = "Gaming", ChildCategory = "Contests" },  
            new Category(){ ParentCategory = "Gaming", ChildCategory = "Fantasy Sports" },  
            new Category(){ ParentCategory = "Gaming", ChildCategory = "Gambling" },  
            new Category(){ ParentCategory = "Gaming", ChildCategory = "Gamification" },  
            new Category(){ ParentCategory = "Gaming", ChildCategory = "Gaming" },  
            new Category(){ ParentCategory = "Gaming", ChildCategory = "MMO Games" },  
            new Category(){ ParentCategory = "Gaming", ChildCategory = "Online Games" },  
            new Category(){ ParentCategory = "Gaming", ChildCategory = "PC Games" },  
            new Category(){ ParentCategory = "Gaming", ChildCategory = "Serious Games" },  
            new Category(){ ParentCategory = "Gaming", ChildCategory = "Video Games" },  
            new Category(){ ParentCategory = "Government and Military", ChildCategory = "CivicTech" },  
            new Category(){ ParentCategory = "Government and Military", ChildCategory = "Government" },  
            new Category(){ ParentCategory = "Government and Military", ChildCategory = "GovTech" },  
            new Category(){ ParentCategory = "Government and Military", ChildCategory = "Law Enforcement" },  
            new Category(){ ParentCategory = "Government and Military", ChildCategory = "Military" },  
            new Category(){ ParentCategory = "Government and Military", ChildCategory = "National Security" },  
            new Category(){ ParentCategory = "Government and Military", ChildCategory = "Politics" },  
            new Category(){ ParentCategory = "Government and Military", ChildCategory = "Public Safety" },  
            new Category(){ ParentCategory = "Government and Military", ChildCategory = "Social Assistance" },  
            new Category(){ ParentCategory = "Hardware", ChildCategory = "3D Technology" },  
            new Category(){ ParentCategory = "Hardware", ChildCategory = "Application Specific Integrated Circuit (ASIC)" },  
            new Category(){ ParentCategory = "Hardware", ChildCategory = "Augmented Reality" },  
            new Category(){ ParentCategory = "Hardware", ChildCategory = "Cloud Infrastructure" },  
            new Category(){ ParentCategory = "Hardware", ChildCategory = "Communication Hardware" },  
            new Category(){ ParentCategory = "Hardware", ChildCategory = "Communications Infrastructure" },  
            new Category(){ ParentCategory = "Hardware", ChildCategory = "Computer" },  
            new Category(){ ParentCategory = "Hardware", ChildCategory = "Computer Vision" },  
            new Category(){ ParentCategory = "Hardware", ChildCategory = "Consumer Electronics" },  
            new Category(){ ParentCategory = "Hardware", ChildCategory = "Data Center" },  
            new Category(){ ParentCategory = "Hardware", ChildCategory = "Data Center Automation" },  
            new Category(){ ParentCategory = "Hardware", ChildCategory = "Data Storage" },  
            new Category(){ ParentCategory = "Hardware", ChildCategory = "Drone Management" },  
            new Category(){ ParentCategory = "Hardware", ChildCategory = "Drones" },  
            new Category(){ ParentCategory = "Hardware", ChildCategory = "DSP" },  
            new Category(){ ParentCategory = "Hardware", ChildCategory = "Electronic Design Automation (EDA)" },  
            new Category(){ ParentCategory = "Hardware", ChildCategory = "Electronics" },  
            new Category(){ ParentCategory = "Hardware", ChildCategory = "Embedded Systems" },  
            new Category(){ ParentCategory = "Hardware", ChildCategory = "Field-Programmable Gate Array (FPGA)" },  
            new Category(){ ParentCategory = "Hardware", ChildCategory = "Flash Storage" },  
            new Category(){ ParentCategory = "Hardware", ChildCategory = "Google Glass" },  
            new Category(){ ParentCategory = "Hardware", ChildCategory = "GPS" },  
            new Category(){ ParentCategory = "Hardware", ChildCategory = "GPU" },  
            new Category(){ ParentCategory = "Hardware", ChildCategory = "Hardware" },  
            new Category(){ ParentCategory = "Hardware", ChildCategory = "Industrial Design" },  
            new Category(){ ParentCategory = "Hardware", ChildCategory = "Laser" },  
            new Category(){ ParentCategory = "Hardware", ChildCategory = "Lighting" },  
            new Category(){ ParentCategory = "Hardware", ChildCategory = "Mechanical Design" },  
            new Category(){ ParentCategory = "Hardware", ChildCategory = "Mobile Devices" },  
            new Category(){ ParentCategory = "Hardware", ChildCategory = "Network Hardware" },  
            new Category(){ ParentCategory = "Hardware", ChildCategory = "NFC" },  
            new Category(){ ParentCategory = "Hardware", ChildCategory = "Nintendo"},  
            new Category(){ ParentCategory = "Hardware", ChildCategory = "Optical Communication"},  
            new Category(){ ParentCategory = "Hardware", ChildCategory = "Playstation"},  
            new Category(){ ParentCategory = "Hardware", ChildCategory = "Private Cloud"},  
            new Category(){ ParentCategory = "Hardware", ChildCategory = "Retail Technology"},  
            new Category(){ ParentCategory = "Hardware", ChildCategory = "RFID"},  
            new Category(){ ParentCategory = "Hardware", ChildCategory = "RISC"},  
            new Category(){ ParentCategory = "Hardware", ChildCategory = "Robotics"},  
            new Category(){ ParentCategory = "Hardware", ChildCategory = "Roku"},  
            new Category(){ ParentCategory = "Hardware", ChildCategory = "Satellite Communication"},  
            new Category(){ ParentCategory = "Hardware", ChildCategory = "Semiconductor"},  
            new Category(){ ParentCategory = "Hardware", ChildCategory = "Sensor"},  
            new Category(){ ParentCategory = "Hardware", ChildCategory = "Sex Tech"},  
            new Category(){ ParentCategory = "Hardware", ChildCategory = "Telecommunications"},  
            new Category(){ ParentCategory = "Hardware", ChildCategory = "Video Conferencing"},  
            new Category(){ ParentCategory = "Hardware", ChildCategory = "Virtual Reality"},  
            new Category(){ ParentCategory = "Hardware", ChildCategory = "Virtualization"},  
            new Category(){ ParentCategory = "Hardware", ChildCategory = "Wearables"},  
            new Category(){ ParentCategory = "Hardware", ChildCategory = "Windows Phone"},  
            new Category(){ ParentCategory = "Hardware", ChildCategory = "Wireless"},  
            new Category(){ ParentCategory = "Hardware", ChildCategory = "Xbox"},  
            new Category(){ ParentCategory = "Health Care", ChildCategory = "Alternative Medicine"},  
            new Category(){ ParentCategory = "Health Care", ChildCategory = "Assisted Living"},  
            new Category(){ ParentCategory = "Health Care", ChildCategory = "Assistive Technology"},  
            new Category(){ ParentCategory = "Health Care", ChildCategory = "Biopharma"},  
            new Category(){ ParentCategory = "Health Care", ChildCategory = "Cannabis"},  
            new Category(){ ParentCategory = "Health Care", ChildCategory = "Child Care"},  
            new Category(){ ParentCategory = "Health Care", ChildCategory = "Clinical Trials"},  
            new Category(){ ParentCategory = "Health Care", ChildCategory = "Cosmetic Surgery"},  
            new Category(){ ParentCategory = "Health Care", ChildCategory = "Dental"},  
            new Category(){ ParentCategory = "Health Care", ChildCategory = "Diabetes"},  
            new Category(){ ParentCategory = "Health Care", ChildCategory = "Dietary Supplements"},  
            new Category(){ ParentCategory = "Health Care", ChildCategory = "Elder Care"},  
            new Category(){ ParentCategory = "Health Care", ChildCategory = "Electronic Health Record (EHR)"},  
            new Category(){ ParentCategory = "Health Care", ChildCategory = "Emergency Medicine"},  
            new Category(){ ParentCategory = "Health Care", ChildCategory = "Employee Benefits"},  
            new Category(){ ParentCategory = "Health Care", ChildCategory = "Fertility"},  
            new Category(){ ParentCategory = "Health Care", ChildCategory = "First Aid"},  
            new Category(){ ParentCategory = "Health Care", ChildCategory = "Funerals"},  
            new Category(){ ParentCategory = "Health Care", ChildCategory = "Genetics"},  
            new Category(){ ParentCategory = "Health Care", ChildCategory = "Health Care"},  
            new Category(){ ParentCategory = "Health Care", ChildCategory = "Health Diagnostics"},  
            new Category(){ ParentCategory = "Health Care", ChildCategory = "Home Health Care"},  
            new Category(){ ParentCategory = "Health Care", ChildCategory = "Hospital"},  
            new Category(){ ParentCategory = "Health Care", ChildCategory = "Medical"},  
            new Category(){ ParentCategory = "Health Care", ChildCategory = "Medical Device"},  
            new Category(){ ParentCategory = "Health Care", ChildCategory = "mHealth"},  
            new Category(){ ParentCategory = "Health Care", ChildCategory = "Nursing and Residential Care"},  
            new Category(){ ParentCategory = "Health Care", ChildCategory = "Nutraceutical"},  
            new Category(){ ParentCategory = "Health Care", ChildCategory = "Nutrition"},  
            new Category(){ ParentCategory = "Health Care", ChildCategory = "Outpatient Care"},  
            new Category(){ ParentCategory = "Health Care", ChildCategory = "Personal Health"},  
            new Category(){ ParentCategory = "Health Care", ChildCategory = "Pharmaceutical"},  
            new Category(){ ParentCategory = "Health Care", ChildCategory = "Psychology"},  
            new Category(){ ParentCategory = "Health Care", ChildCategory = "Rehabilitation"},  
            new Category(){ ParentCategory = "Health Care", ChildCategory = "Therapeutics"},  
            new Category(){ ParentCategory = "Health Care", ChildCategory = "Veterinary"},  
            new Category(){ ParentCategory = "Health Care", ChildCategory = "Wellness"},  
            new Category(){ ParentCategory = "Information Technology", ChildCategory = "Business Information Systems"},  
            new Category(){ ParentCategory = "Information Technology", ChildCategory = "CivicTech"},  
            new Category(){ ParentCategory = "Information Technology", ChildCategory = "Cloud Data Services"},  
            new Category(){ ParentCategory = "Information Technology", ChildCategory = "Cloud Management"},  
            new Category(){ ParentCategory = "Information Technology", ChildCategory = "Cloud Security"},  
            new Category(){ ParentCategory = "Information Technology", ChildCategory = "CMS"},  
            new Category(){ ParentCategory = "Information Technology", ChildCategory = "Contact Management"},  
            new Category(){ ParentCategory = "Information Technology", ChildCategory = "CRM"},  
            new Category(){ ParentCategory = "Information Technology", ChildCategory = "Cyber Security"},  
            new Category(){ ParentCategory = "Information Technology", ChildCategory = "Data Center"},  
            new Category(){ ParentCategory = "Information Technology", ChildCategory = "Data Center Automation"},  
            new Category(){ ParentCategory = "Information Technology", ChildCategory = "Data Integration"},  
            new Category(){ ParentCategory = "Information Technology", ChildCategory = "Data Mining"},  
            new Category(){ ParentCategory = "Information Technology", ChildCategory = "Data Visualization"},  
            new Category(){ ParentCategory = "Information Technology", ChildCategory = "Document Management"},  
            new Category(){ ParentCategory = "Information Technology", ChildCategory = "E-Signature"},  
            new Category(){ ParentCategory = "Information Technology", ChildCategory = "Email"},  
            new Category(){ ParentCategory = "Information Technology", ChildCategory = "GovTech"},  
            new Category(){ ParentCategory = "Information Technology", ChildCategory = "Identity Management"},  
            new Category(){ ParentCategory = "Information Technology", ChildCategory = "Information and Communications Technology (ICT)"},  
            new Category(){ ParentCategory = "Information Technology", ChildCategory = "Information Services"},  
            new Category(){ ParentCategory = "Information Technology", ChildCategory = "Information Technology"},  
            new Category(){ ParentCategory = "Information Technology", ChildCategory = "Intrusion Detection"},  
            new Category(){ ParentCategory = "Information Technology", ChildCategory = "IT Infrastructure"},  
            new Category(){ ParentCategory = "Information Technology", ChildCategory = "IT Management"},  
            new Category(){ ParentCategory = "Information Technology", ChildCategory = "Management Information Systems"},  
            new Category(){ ParentCategory = "Information Technology", ChildCategory = "Messaging"},  
            new Category(){ ParentCategory = "Information Technology", ChildCategory = "Military"},  
            new Category(){ ParentCategory = "Information Technology", ChildCategory = "Network Security"},  
            new Category(){ ParentCategory = "Information Technology", ChildCategory = "Penetration Testing"},  
            new Category(){ ParentCategory = "Information Technology", ChildCategory = "Private Cloud"},  
            new Category(){ ParentCategory = "Information Technology", ChildCategory = "Reputation"},  
            new Category(){ ParentCategory = "Information Technology", ChildCategory = "Sales Automation"},  
            new Category(){ ParentCategory = "Information Technology", ChildCategory = "Scheduling"},  
            new Category(){ ParentCategory = "Information Technology", ChildCategory = "Social CRM"},  
            new Category(){ ParentCategory = "Information Technology", ChildCategory = "Spam Filtering"},  
            new Category(){ ParentCategory = "Information Technology", ChildCategory = "Unified Communications"},  
            new Category(){ ParentCategory = "Information Technology", ChildCategory = "Video Chat"},  
            new Category(){ ParentCategory = "Information Technology", ChildCategory = "Video Conferencing"},  
            new Category(){ ParentCategory = "Information Technology", ChildCategory = "Virtualization"},  
            new Category(){ ParentCategory = "Information Technology", ChildCategory = "VoIP"},  
            new Category(){ ParentCategory = "Internet Services", ChildCategory = "Cloud Computing"},  
            new Category(){ ParentCategory = "Internet Services", ChildCategory = "Cloud Data Services"},  
            new Category(){ ParentCategory = "Internet Services", ChildCategory = "Cloud Infrastructure"},  
            new Category(){ ParentCategory = "Internet Services", ChildCategory = "Cloud Management"},  
            new Category(){ ParentCategory = "Internet Services", ChildCategory = "Cloud Storage"},  
            new Category(){ ParentCategory = "Internet Services", ChildCategory = "Darknet"},  
            new Category(){ ParentCategory = "Internet Services", ChildCategory = "Domain Registrar"},  
            new Category(){ ParentCategory = "Internet Services", ChildCategory = "E-Commerce Platforms"},  
            new Category(){ ParentCategory = "Internet Services", ChildCategory = "Ediscovery"},  
            new Category(){ ParentCategory = "Internet Services", ChildCategory = "Email"},  
            new Category(){ ParentCategory = "Internet Services", ChildCategory = "Internet"},  
            new Category(){ ParentCategory = "Internet Services", ChildCategory = "Internet of Things"},  
            new Category(){ ParentCategory = "Internet Services", ChildCategory = "ISP"},  
            new Category(){ ParentCategory = "Internet Services", ChildCategory = "Location Based Services"},  
            new Category(){ ParentCategory = "Internet Services", ChildCategory = "Messaging"},  
            new Category(){ ParentCategory = "Internet Services", ChildCategory = "Music Streaming"},  
            new Category(){ ParentCategory = "Internet Services", ChildCategory = "Online Forums"},  
            new Category(){ ParentCategory = "Internet Services", ChildCategory = "Online Portals"},  
            new Category(){ ParentCategory = "Internet Services", ChildCategory = "Private Cloud"},  
            new Category(){ ParentCategory = "Internet Services", ChildCategory = "Product Search"},  
            new Category(){ ParentCategory = "Internet Services", ChildCategory = "Search Engine"},  
            new Category(){ ParentCategory = "Internet Services", ChildCategory = "SEM"},  
            new Category(){ ParentCategory = "Internet Services", ChildCategory = "Semantic Search"},  
            new Category(){ ParentCategory = "Internet Services", ChildCategory = "Semantic Web"},  
            new Category(){ ParentCategory = "Internet Services", ChildCategory = "SEO"},  
            new Category(){ ParentCategory = "Internet Services", ChildCategory = "SMS"},  
            new Category(){ ParentCategory = "Internet Services", ChildCategory = "Social Media"},  
            new Category(){ ParentCategory = "Internet Services", ChildCategory = "Social Media Management"},  
            new Category(){ ParentCategory = "Internet Services", ChildCategory = "Social Network"},  
            new Category(){ ParentCategory = "Internet Services", ChildCategory = "Unified Communications"},  
            new Category(){ ParentCategory = "Internet Services", ChildCategory = "Vertical Search"},  
            new Category(){ ParentCategory = "Internet Services", ChildCategory = "Video Chat"},  
            new Category(){ ParentCategory = "Internet Services", ChildCategory = "Video Conferencing"},  
            new Category(){ ParentCategory = "Internet Services", ChildCategory = "Visual Search"},  
            new Category(){ ParentCategory = "Internet Services", ChildCategory = "VoIP"},  
            new Category(){ ParentCategory = "Internet Services", ChildCategory = "Web Browsers"},  
            new Category(){ ParentCategory = "Lending and Investments", ChildCategory = "Angel Investment"},  
            new Category(){ ParentCategory = "Lending and Investments", ChildCategory = "Banking"},  
            new Category(){ ParentCategory = "Lending and Investments", ChildCategory = "Commercial Lending"},  
            new Category(){ ParentCategory = "Lending and Investments", ChildCategory = "Consumer Lending"},  
            new Category(){ ParentCategory = "Lending and Investments", ChildCategory = "Credit"},  
            new Category(){ ParentCategory = "Lending and Investments", ChildCategory = "Credit Cards"},  
            new Category(){ ParentCategory = "Lending and Investments", ChildCategory = "Financial Exchanges"},  
            new Category(){ ParentCategory = "Lending and Investments", ChildCategory = "Funding Platform"},  
            new Category(){ ParentCategory = "Lending and Investments", ChildCategory = "Hedge Funds"},  
            new Category(){ ParentCategory = "Lending and Investments", ChildCategory = "Impact Investing"},  
            new Category(){ ParentCategory = "Lending and Investments", ChildCategory = "Incubators"},  
            new Category(){ ParentCategory = "Lending and Investments", ChildCategory = "Micro Lending"},  
            new Category(){ ParentCategory = "Lending and Investments", ChildCategory = "Stock Exchanges"},  
            new Category(){ ParentCategory = "Lending and Investments", ChildCategory = "Trading Platform"},  
            new Category(){ ParentCategory = "Lending and Investments", ChildCategory = "Venture Capital"},  
            new Category(){ ParentCategory = "Manufacturing", ChildCategory = "3D Printing"},  
            new Category(){ ParentCategory = "Manufacturing", ChildCategory = "Advanced Materials"},  
            new Category(){ ParentCategory = "Manufacturing", ChildCategory = "Foundries"},  
            new Category(){ ParentCategory = "Manufacturing", ChildCategory = "Industrial Automation"},  
            new Category(){ ParentCategory = "Manufacturing", ChildCategory = "Industrial Engineering"},  
            new Category(){ ParentCategory = "Manufacturing", ChildCategory = "Industrial Manufacturing"},  
            new Category(){ ParentCategory = "Manufacturing", ChildCategory = "Machinery Manufacturing"},  
            new Category(){ ParentCategory = "Manufacturing", ChildCategory = "Manufacturing"},  
            new Category(){ ParentCategory = "Manufacturing", ChildCategory = "Paper Manufacturing"},  
            new Category(){ ParentCategory = "Manufacturing", ChildCategory = "Plastics and Rubber Manufacturing"},  
            new Category(){ ParentCategory = "Manufacturing", ChildCategory = "Textiles"},  
            new Category(){ ParentCategory = "Manufacturing", ChildCategory = "Wood Processing"},  
            new Category(){ ParentCategory = "Media and Entertainment", ChildCategory = "Advice"},  
            new Category(){ ParentCategory = "Media and Entertainment", ChildCategory = "Animation"},  
            new Category(){ ParentCategory = "Media and Entertainment", ChildCategory = "Art"},  
            new Category(){ ParentCategory = "Media and Entertainment", ChildCategory = "Audio"},  
            new Category(){ ParentCategory = "Media and Entertainment", ChildCategory = "Audiobooks"},  
            new Category(){ ParentCategory = "Media and Entertainment", ChildCategory = "Blogging Platforms"},  
            new Category(){ ParentCategory = "Media and Entertainment", ChildCategory = "Broadcasting"},  
            new Category(){ ParentCategory = "Media and Entertainment", ChildCategory = "Celebrity"},  
            new Category(){ ParentCategory = "Media and Entertainment", ChildCategory = "Concerts"},  
            new Category(){ ParentCategory = "Media and Entertainment", ChildCategory = "Content"},  
            new Category(){ ParentCategory = "Media and Entertainment", ChildCategory = "Content Creators"},  
            new Category(){ ParentCategory = "Media and Entertainment", ChildCategory = "Content Discovery"},  
            new Category(){ ParentCategory = "Media and Entertainment", ChildCategory = "Content Syndication"},  
            new Category(){ ParentCategory = "Media and Entertainment", ChildCategory = "Creative Agency"},  
            new Category(){ ParentCategory = "Media and Entertainment", ChildCategory = "Digital Entertainment"},  
            new Category(){ ParentCategory = "Media and Entertainment", ChildCategory = "Digital Media"},  
            new Category(){ ParentCategory = "Media and Entertainment", ChildCategory = "DRM"},  
            new Category(){ ParentCategory = "Media and Entertainment", ChildCategory = "EBooks"},  
            new Category(){ ParentCategory = "Media and Entertainment", ChildCategory = "Edutainment"},  
            new Category(){ ParentCategory = "Media and Entertainment", ChildCategory = "Event Management"},  
            new Category(){ ParentCategory = "Media and Entertainment", ChildCategory = "Event Promotion"},  
            new Category(){ ParentCategory = "Media and Entertainment", ChildCategory = "Events"},  
            new Category(){ ParentCategory = "Media and Entertainment", ChildCategory = "Film"},  
            new Category(){ ParentCategory = "Media and Entertainment", ChildCategory = "Film Distribution"},  
            new Category(){ ParentCategory = "Media and Entertainment", ChildCategory = "Film Production"},  
            new Category(){ ParentCategory = "Media and Entertainment", ChildCategory = "Guides"},  
            new Category(){ ParentCategory = "Media and Entertainment", ChildCategory = "In-Flight Entertainment"},  
            new Category(){ ParentCategory = "Media and Entertainment", ChildCategory = "Independent Music"},  
            new Category(){ ParentCategory = "Media and Entertainment", ChildCategory = "Internet Radio"},  
            new Category(){ ParentCategory = "Media and Entertainment", ChildCategory = "Journalism"},  
            new Category(){ ParentCategory = "Media and Entertainment", ChildCategory = "Media and Entertainment"},  
            new Category(){ ParentCategory = "Media and Entertainment", ChildCategory = "Motion Capture"},  
            new Category(){ ParentCategory = "Media and Entertainment", ChildCategory = "Music"},  
            new Category(){ ParentCategory = "Media and Entertainment", ChildCategory = "Music Education"},  
            new Category(){ ParentCategory = "Media and Entertainment", ChildCategory = "Music Label"},  
            new Category(){ ParentCategory = "Media and Entertainment", ChildCategory = "Music Streaming"},  
            new Category(){ ParentCategory = "Media and Entertainment", ChildCategory = "Music Venues"},  
            new Category(){ ParentCategory = "Media and Entertainment", ChildCategory = "Musical Instruments"},  
            new Category(){ ParentCategory = "Media and Entertainment", ChildCategory = "News"},  
            new Category(){ ParentCategory = "Media and Entertainment", ChildCategory = "Nightclubs"},  
            new Category(){ ParentCategory = "Media and Entertainment", ChildCategory = "Nightlife"},  
            new Category(){ ParentCategory = "Media and Entertainment", ChildCategory = "Performing Arts"},  
            new Category(){ ParentCategory = "Media and Entertainment", ChildCategory = "Photo Editing"},  
            new Category(){ ParentCategory = "Media and Entertainment", ChildCategory = "Photo Sharing"},  
            new Category(){ ParentCategory = "Media and Entertainment", ChildCategory = "Photography"},  
            new Category(){ ParentCategory = "Media and Entertainment", ChildCategory = "Podcast"},  
            new Category(){ ParentCategory = "Media and Entertainment", ChildCategory = "Printing"},  
            new Category(){ ParentCategory = "Media and Entertainment", ChildCategory = "Publishing"},  
            new Category(){ ParentCategory = "Media and Entertainment", ChildCategory = "Reservations"},  
            new Category(){ ParentCategory = "Media and Entertainment", ChildCategory = "Social Media"},  
            new Category(){ ParentCategory = "Media and Entertainment", ChildCategory = "Social News"},  
            new Category(){ ParentCategory = "Media and Entertainment", ChildCategory = "Theatre"},  
            new Category(){ ParentCategory = "Media and Entertainment", ChildCategory = "Ticketing"},  
            new Category(){ ParentCategory = "Media and Entertainment", ChildCategory = "TV"},  
            new Category(){ ParentCategory = "Media and Entertainment", ChildCategory = "TV Production"},  
            new Category(){ ParentCategory = "Media and Entertainment", ChildCategory = "Video"},  
            new Category(){ ParentCategory = "Media and Entertainment", ChildCategory = "Video Editing"},  
            new Category(){ ParentCategory = "Media and Entertainment", ChildCategory = "Video on Demand"},  
            new Category(){ ParentCategory = "Media and Entertainment", ChildCategory = "Video Streaming"},  
            new Category(){ ParentCategory = "Media and Entertainment", ChildCategory = "Virtual World"},  
            new Category(){ ParentCategory = "Messaging and Telecommunications", ChildCategory = "Email"},  
            new Category(){ ParentCategory = "Messaging and Telecommunications", ChildCategory = "Meeting Software"},  
            new Category(){ ParentCategory = "Messaging and Telecommunications", ChildCategory = "Messaging"},  
            new Category(){ ParentCategory = "Messaging and Telecommunications", ChildCategory = "SMS"},  
            new Category(){ ParentCategory = "Messaging and Telecommunications", ChildCategory = "Unified Communications"},  
            new Category(){ ParentCategory = "Messaging and Telecommunications", ChildCategory = "Video Chat"},  
            new Category(){ ParentCategory = "Messaging and Telecommunications", ChildCategory = "Video Conferencing"},  
            new Category(){ ParentCategory = "Messaging and Telecommunications", ChildCategory = "VoIP"},  
            new Category(){ ParentCategory = "Messaging and Telecommunications", ChildCategory = "Wired Telecommunications"},  
            new Category(){ ParentCategory = "Mobile", ChildCategory = "Android"},  
            new Category(){ ParentCategory = "Mobile", ChildCategory = "Google Glass"},  
            new Category(){ ParentCategory = "Mobile", ChildCategory = "iOS"},  
            new Category(){ ParentCategory = "Mobile", ChildCategory = "mHealth"},  
            new Category(){ ParentCategory = "Mobile", ChildCategory = "Mobile"},  
            new Category(){ ParentCategory = "Mobile", ChildCategory = "Mobile Apps"},  
            new Category(){ ParentCategory = "Mobile", ChildCategory = "Mobile Devices"},  
            new Category(){ ParentCategory = "Mobile", ChildCategory = "Mobile Payments"},  
            new Category(){ ParentCategory = "Mobile", ChildCategory = "Windows Phone"},  
            new Category(){ ParentCategory = "Mobile", ChildCategory = "Wireless"},  
            new Category(){ ParentCategory = "Music and Audio", ChildCategory = "Audio"},  
            new Category(){ ParentCategory = "Music and Audio", ChildCategory = "Audiobooks"},  
            new Category(){ ParentCategory = "Music and Audio", ChildCategory = "Independent Music"},  
            new Category(){ ParentCategory = "Music and Audio", ChildCategory = "Internet Radio"},  
            new Category(){ ParentCategory = "Music and Audio", ChildCategory = "Music"},  
            new Category(){ ParentCategory = "Music and Audio", ChildCategory = "Music Education"},  
            new Category(){ ParentCategory = "Music and Audio", ChildCategory = "Music Label"},  
            new Category(){ ParentCategory = "Music and Audio", ChildCategory = "Music Streaming"},  
            new Category(){ ParentCategory = "Music and Audio", ChildCategory = "Musical Instruments"},  
            new Category(){ ParentCategory = "Music and Audio", ChildCategory = "Podcast"},  
            new Category(){ ParentCategory = "Natural Resources", ChildCategory = "Biofuel"},  
            new Category(){ ParentCategory = "Natural Resources", ChildCategory = "Biomass Energy"},  
            new Category(){ ParentCategory = "Natural Resources", ChildCategory = "Fossil Fuels"},  
            new Category(){ ParentCategory = "Natural Resources", ChildCategory = "Mineral"},  
            new Category(){ ParentCategory = "Natural Resources", ChildCategory = "Mining"},  
            new Category(){ ParentCategory = "Natural Resources", ChildCategory = "Mining Technology"},  
            new Category(){ ParentCategory = "Natural Resources", ChildCategory = "Natural Resources"},  
            new Category(){ ParentCategory = "Natural Resources", ChildCategory = "Oil and Gas"},  
            new Category(){ ParentCategory = "Natural Resources", ChildCategory = "Precious Metals"},  
            new Category(){ ParentCategory = "Natural Resources", ChildCategory = "Solar"},  
            new Category(){ ParentCategory = "Natural Resources", ChildCategory = "Timber"},  
            new Category(){ ParentCategory = "Natural Resources", ChildCategory = "Water"},  
            new Category(){ ParentCategory = "Natural Resources", ChildCategory = "Wind Energy"},  
            new Category(){ ParentCategory = "Navigation and Mapping", ChildCategory = "Geospatial"},  
            new Category(){ ParentCategory = "Navigation and Mapping", ChildCategory = "GPS"},  
            new Category(){ ParentCategory = "Navigation and Mapping", ChildCategory = "Indoor Positioning"},  
            new Category(){ ParentCategory = "Navigation and Mapping", ChildCategory = "Location Based Services"},  
            new Category(){ ParentCategory = "Navigation and Mapping", ChildCategory = "Mapping Services"},  
            new Category(){ ParentCategory = "Navigation and Mapping", ChildCategory = "Navigation"},  
            new Category(){ ParentCategory = "Payments", ChildCategory = "Billing"},  
            new Category(){ ParentCategory = "Payments", ChildCategory = "Bitcoin"},  
            new Category(){ ParentCategory = "Payments", ChildCategory = "Credit Cards"},  
            new Category(){ ParentCategory = "Payments", ChildCategory = "Cryptocurrency"},  
            new Category(){ ParentCategory = "Payments", ChildCategory = "Debit Cards"},  
            new Category(){ ParentCategory = "Payments", ChildCategory = "Fraud Detection"},  
            new Category(){ ParentCategory = "Payments", ChildCategory = "Mobile Payments"},  
            new Category(){ ParentCategory = "Payments", ChildCategory = "Payments"},  
            new Category(){ ParentCategory = "Payments", ChildCategory = "Transaction Processing"},  
            new Category(){ ParentCategory = "Payments", ChildCategory = "Virtual Currency"},  
            new Category(){ ParentCategory = "Platforms", ChildCategory = "Android"},  
            new Category(){ ParentCategory = "Platforms", ChildCategory = "Facebook"},  
            new Category(){ ParentCategory = "Platforms", ChildCategory = "Google"},  
            new Category(){ ParentCategory = "Platforms", ChildCategory = "Google Glass"},  
            new Category(){ ParentCategory = "Platforms", ChildCategory = "iOS"},  
            new Category(){ ParentCategory = "Platforms", ChildCategory = "Linux"},  
            new Category(){ ParentCategory = "Platforms", ChildCategory = "macOS"},  
            new Category(){ ParentCategory = "Platforms", ChildCategory = "Nintendo"},  
            new Category(){ ParentCategory = "Platforms", ChildCategory = "Operating Systems"},  
            new Category(){ ParentCategory = "Platforms", ChildCategory = "Playstation"},  
            new Category(){ ParentCategory = "Platforms", ChildCategory = "Roku"},  
            new Category(){ ParentCategory = "Platforms", ChildCategory = "Tizen"},  
            new Category(){ ParentCategory = "Platforms", ChildCategory = "Twitter"},  
            new Category(){ ParentCategory = "Platforms", ChildCategory = "WebOS"},  
            new Category(){ ParentCategory = "Platforms", ChildCategory = "Windows"},  
            new Category(){ ParentCategory = "Platforms", ChildCategory = "Windows Phone"},  
            new Category(){ ParentCategory = "Platforms", ChildCategory = "Xbox"},  
            new Category(){ ParentCategory = "Privacy and Security", ChildCategory = "Cloud Security"},  
            new Category(){ ParentCategory = "Privacy and Security", ChildCategory = "Corrections Facilities"},  
            new Category(){ ParentCategory = "Privacy and Security", ChildCategory = "Cyber Security"},  
            new Category(){ ParentCategory = "Privacy and Security", ChildCategory = "DRM"},  
            new Category(){ ParentCategory = "Privacy and Security", ChildCategory = "E-Signature"},  
            new Category(){ ParentCategory = "Privacy and Security", ChildCategory = "Fraud Detection"},  
            new Category(){ ParentCategory = "Privacy and Security", ChildCategory = "Homeland Security"},  
            new Category(){ ParentCategory = "Privacy and Security", ChildCategory = "Identity Management"},  
            new Category(){ ParentCategory = "Privacy and Security", ChildCategory = "Intrusion Detection"},  
            new Category(){ ParentCategory = "Privacy and Security", ChildCategory = "Law Enforcement"},  
            new Category(){ ParentCategory = "Privacy and Security", ChildCategory = "Network Security"},  
            new Category(){ ParentCategory = "Privacy and Security", ChildCategory = "Penetration Testing"},  
            new Category(){ ParentCategory = "Privacy and Security", ChildCategory = "Physical Security"},  
            new Category(){ ParentCategory = "Privacy and Security", ChildCategory = "Privacy"},  
            new Category(){ ParentCategory = "Privacy and Security", ChildCategory = "Security"},  
            new Category(){ ParentCategory = "Professional Services", ChildCategory = "Accounting"},  
            new Category(){ ParentCategory = "Professional Services", ChildCategory = "Career Planning"},  
            new Category(){ ParentCategory = "Professional Services", ChildCategory = "Compliance"},  
            new Category(){ ParentCategory = "Professional Services", ChildCategory = "Employment"},  
            new Category(){ ParentCategory = "Professional Services", ChildCategory = "Environmental Consulting"},  
            new Category(){ ParentCategory = "Professional Services", ChildCategory = "Freelance"},  
            new Category(){ ParentCategory = "Professional Services", ChildCategory = "Intellectual Property"},  
            new Category(){ ParentCategory = "Professional Services", ChildCategory = "Legal"},  
            new Category(){ ParentCategory = "Professional Services", ChildCategory = "Legal Tech"},  
            new Category(){ ParentCategory = "Professional Services", ChildCategory = "Management Consulting"},  
            new Category(){ ParentCategory = "Professional Services", ChildCategory = "Outsourcing"},  
            new Category(){ ParentCategory = "Professional Services", ChildCategory = "Professional Networking"},  
            new Category(){ ParentCategory = "Professional Services", ChildCategory = "Recruiting"},  
            new Category(){ ParentCategory = "Professional Services", ChildCategory = "Social Recruiting"},  
            new Category(){ ParentCategory = "Professional Services", ChildCategory = "Translation Service"},  
            new Category(){ ParentCategory = "Real Estate", ChildCategory = "Architecture"},  
            new Category(){ ParentCategory = "Real Estate", ChildCategory = "Building Maintenance"},  
            new Category(){ ParentCategory = "Real Estate", ChildCategory = "Building Material"},  
            new Category(){ ParentCategory = "Real Estate", ChildCategory = "Commercial Real Estate"},  
            new Category(){ ParentCategory = "Real Estate", ChildCategory = "Construction"},  
            new Category(){ ParentCategory = "Real Estate", ChildCategory = "Coworking"},  
            new Category(){ ParentCategory = "Real Estate", ChildCategory = "Facility Management"},  
            new Category(){ ParentCategory = "Real Estate", ChildCategory = "Fast-Moving Consumer Goods"},  
            new Category(){ ParentCategory = "Real Estate", ChildCategory = "Green Building"},  
            new Category(){ ParentCategory = "Real Estate", ChildCategory = "Home and Garden"},  
            new Category(){ ParentCategory = "Real Estate", ChildCategory = "Home Decor"},  
            new Category(){ ParentCategory = "Real Estate", ChildCategory = "Home Improvement"},  
            new Category(){ ParentCategory = "Real Estate", ChildCategory = "Home Renovation"},  
            new Category(){ ParentCategory = "Real Estate", ChildCategory = "Home Services"},  
            new Category(){ ParentCategory = "Real Estate", ChildCategory = "Interior Design"},  
            new Category(){ ParentCategory = "Real Estate", ChildCategory = "Janitorial Service"},  
            new Category(){ ParentCategory = "Real Estate", ChildCategory = "Landscaping"},  
            new Category(){ ParentCategory = "Real Estate", ChildCategory = "Property Development"},  
            new Category(){ ParentCategory = "Real Estate", ChildCategory = "Property Management"},  
            new Category(){ ParentCategory = "Real Estate", ChildCategory = "Real Estate"},  
            new Category(){ ParentCategory = "Real Estate", ChildCategory = "Real Estate Investment"},  
            new Category(){ ParentCategory = "Real Estate", ChildCategory = "Rental Property"},  
            new Category(){ ParentCategory = "Real Estate", ChildCategory = "Self-Storage"},  
            new Category(){ ParentCategory = "Real Estate", ChildCategory = "Smart Building"},  
            new Category(){ ParentCategory = "Real Estate", ChildCategory = "Smart Cities"},  
            new Category(){ ParentCategory = "Real Estate", ChildCategory = "Smart Home"},  
            new Category(){ ParentCategory = "Real Estate", ChildCategory = "Timeshare"},  
            new Category(){ ParentCategory = "Real Estate", ChildCategory = "Vacation Rental"},  
            new Category(){ ParentCategory = "Sales and Marketing", ChildCategory = "Advertising"},  
            new Category(){ ParentCategory = "Sales and Marketing", ChildCategory = "Affiliate Marketing"},  
            new Category(){ ParentCategory = "Sales and Marketing", ChildCategory = "App Discovery"},  
            new Category(){ ParentCategory = "Sales and Marketing", ChildCategory = "App Marketing"},  
            new Category(){ ParentCategory = "Sales and Marketing", ChildCategory = "Brand Marketing"},  
            new Category(){ ParentCategory = "Sales and Marketing", ChildCategory = "Cause Marketing"},  
            new Category(){ ParentCategory = "Sales and Marketing", ChildCategory = "Content Marketing"},  
            new Category(){ ParentCategory = "Sales and Marketing", ChildCategory = "CRM"},  
            new Category(){ ParentCategory = "Sales and Marketing", ChildCategory = "Digital Marketing"},  
            new Category(){ ParentCategory = "Sales and Marketing", ChildCategory = "Digital Signage"},  
            new Category(){ ParentCategory = "Sales and Marketing", ChildCategory = "Direct Marketing"},  
            new Category(){ ParentCategory = "Sales and Marketing", ChildCategory = "Direct Sales"},  
            new Category(){ ParentCategory = "Sales and Marketing", ChildCategory = "Email Marketing"},  
            new Category(){ ParentCategory = "Sales and Marketing", ChildCategory = "Lead Generation"},  
            new Category(){ ParentCategory = "Sales and Marketing", ChildCategory = "Lead Management"},  
            new Category(){ ParentCategory = "Sales and Marketing", ChildCategory = "Local Advertising"},  
            new Category(){ ParentCategory = "Sales and Marketing", ChildCategory = "Loyalty Programs"},  
            new Category(){ ParentCategory = "Sales and Marketing", ChildCategory = "Marketing"},  
            new Category(){ ParentCategory = "Sales and Marketing", ChildCategory = "Marketing Automation"},  
            new Category(){ ParentCategory = "Sales and Marketing", ChildCategory = "Mobile Advertising"},  
            new Category(){ ParentCategory = "Sales and Marketing", ChildCategory = "Multi-level Marketing"},  
            new Category(){ ParentCategory = "Sales and Marketing", ChildCategory = "Outdoor Advertising"},  
            new Category(){ ParentCategory = "Sales and Marketing", ChildCategory = "Personal Branding"},  
            new Category(){ ParentCategory = "Sales and Marketing", ChildCategory = "Public Relations"},  
            new Category(){ ParentCategory = "Sales and Marketing", ChildCategory = "Sales"},  
            new Category(){ ParentCategory = "Sales and Marketing", ChildCategory = "Sales Automation"},  
            new Category(){ ParentCategory = "Sales and Marketing", ChildCategory = "SEM"},  
            new Category(){ ParentCategory = "Sales and Marketing", ChildCategory = "SEO"},  
            new Category(){ ParentCategory = "Sales and Marketing", ChildCategory = "Social CRM"},  
            new Category(){ ParentCategory = "Sales and Marketing", ChildCategory = "Social Media Advertising"},  
            new Category(){ ParentCategory = "Sales and Marketing", ChildCategory = "Social Media Management"},  
            new Category(){ ParentCategory = "Sales and Marketing", ChildCategory = "Social Media Marketing"},  
            new Category(){ ParentCategory = "Sales and Marketing", ChildCategory = "Sponsorship"},  
            new Category(){ ParentCategory = "Sales and Marketing", ChildCategory = "Video Advertising"},  
            new Category(){ ParentCategory = "Science and Engineering", ChildCategory = "Advanced Materials"},  
            new Category(){ ParentCategory = "Science and Engineering", ChildCategory = "Aerospace"},  
            new Category(){ ParentCategory = "Science and Engineering", ChildCategory = "Artificial Intelligence"},  
            new Category(){ ParentCategory = "Science and Engineering", ChildCategory = "Bioinformatics"},  
            new Category(){ ParentCategory = "Science and Engineering", ChildCategory = "Biometrics"},  
            new Category(){ ParentCategory = "Science and Engineering", ChildCategory = "Biopharma"},  
            new Category(){ ParentCategory = "Science and Engineering", ChildCategory = "Biotechnology"},  
            new Category(){ ParentCategory = "Science and Engineering", ChildCategory = "Chemical"},  
            new Category(){ ParentCategory = "Science and Engineering", ChildCategory = "Chemical Engineering"},  
            new Category(){ ParentCategory = "Science and Engineering", ChildCategory = "Civil Engineering"},  
            new Category(){ ParentCategory = "Science and Engineering", ChildCategory = "Embedded Systems"},  
            new Category(){ ParentCategory = "Science and Engineering", ChildCategory = "Environmental Engineering"},  
            new Category(){ ParentCategory = "Science and Engineering", ChildCategory = "Human Computer Interaction"},  
            new Category(){ ParentCategory = "Science and Engineering", ChildCategory = "Industrial Automation"},  
            new Category(){ ParentCategory = "Science and Engineering", ChildCategory = "Industrial Engineering"},  
            new Category(){ ParentCategory = "Science and Engineering", ChildCategory = "Intelligent Systems"},  
            new Category(){ ParentCategory = "Science and Engineering", ChildCategory = "Laser"},  
            new Category(){ ParentCategory = "Science and Engineering", ChildCategory = "Life Science"},  
            new Category(){ ParentCategory = "Science and Engineering", ChildCategory = "Marine Technology"},  
            new Category(){ ParentCategory = "Science and Engineering", ChildCategory = "Mechanical Engineering"},  
            new Category(){ ParentCategory = "Science and Engineering", ChildCategory = "Nanotechnology"},  
            new Category(){ ParentCategory = "Science and Engineering", ChildCategory = "Neuroscience"},  
            new Category(){ ParentCategory = "Science and Engineering", ChildCategory = "Nuclear"},  
            new Category(){ ParentCategory = "Science and Engineering", ChildCategory = "Quantum Computing"},  
            new Category(){ ParentCategory = "Science and Engineering", ChildCategory = "Robotics"},  
            new Category(){ ParentCategory = "Science and Engineering", ChildCategory = "Semiconductor"},  
            new Category(){ ParentCategory = "Science and Engineering", ChildCategory = "Software Engineering"},  
            new Category(){ ParentCategory = "Science and Engineering", ChildCategory = "STEM Education"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "3D Technology"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "Android"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "App Discovery"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "Application Performance Management"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "Apps"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "Artificial Intelligence"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "Augmented Reality"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "Billing"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "Bitcoin"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "Browser Extensions"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "CAD"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "Cloud Computing"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "Cloud Management"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "CMS"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "Computer Vision"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "Consumer Applications"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "Consumer Software"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "Contact Management"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "CRM"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "Cryptocurrency"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "Data Center Automation"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "Data Integration"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "Data Storage"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "Data Visualization"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "Database"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "Developer APIs"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "Developer Platform"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "Developer Tools"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "Document Management"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "Drone Management"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "E-Learning"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "EdTech"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "Electronic Design Automation (EDA)"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "Embedded Software"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "Embedded Systems"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "Enterprise Applications"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "Enterprise Resource Planning (ERP)"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "Enterprise Software"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "Facial Recognition"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "File Sharing"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "IaaS"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "Image Recognition"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "iOS"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "Linux"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "Machine Learning"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "macOS"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "Marketing Automation"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "Meeting Software"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "Mobile Apps"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "Mobile Payments"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "MOOC"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "Natural Language Processing"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "Open Source"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "Operating Systems"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "PaaS"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "Predictive Analytics"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "Presentation Software"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "Presentations"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "Private Cloud"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "Productivity Tools"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "QR Codes"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "Reading Apps"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "Retail Technology"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "Robotics"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "SaaS"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "Sales Automation"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "Scheduling"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "Sex Tech"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "Simulation"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "SNS"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "Social CRM"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "Software"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "Software Engineering"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "Speech Recognition"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "Task Management"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "Text Analytics"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "Transaction Processing"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "Video Conferencing"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "Virtual Assistant"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "Virtual Currency"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "Virtual Desktop"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "Virtual Goods"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "Virtual Reality"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "Virtual World"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "Virtualization"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "Web Apps"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "Web Browsers"},  
            new Category(){ ParentCategory = "Software", ChildCategory = "Web Development"},  
            new Category(){ ParentCategory = "Sports", ChildCategory = "American Football"},  
            new Category(){ ParentCategory = "Sports", ChildCategory = "Baseball"},  
            new Category(){ ParentCategory = "Sports", ChildCategory = "Basketball"},  
            new Category(){ ParentCategory = "Sports", ChildCategory = "Boating"},  
            new Category(){ ParentCategory = "Sports", ChildCategory = "Cricket"},  
            new Category(){ ParentCategory = "Sports", ChildCategory = "Cycling"},  
            new Category(){ ParentCategory = "Sports", ChildCategory = "Diving"},  
            new Category(){ ParentCategory = "Sports", ChildCategory = "eSports"},  
            new Category(){ ParentCategory = "Sports", ChildCategory = "Fantasy Sports"},  
            new Category(){ ParentCategory = "Sports", ChildCategory = "Fitness"},  
            new Category(){ ParentCategory = "Sports", ChildCategory = "Golf"},  
            new Category(){ ParentCategory = "Sports", ChildCategory = "Hockey"},  
            new Category(){ ParentCategory = "Sports", ChildCategory = "Hunting"},  
            new Category(){ ParentCategory = "Sports", ChildCategory = "Outdoors"},  
            new Category(){ ParentCategory = "Sports", ChildCategory = "Racing"},  
            new Category(){ ParentCategory = "Sports", ChildCategory = "Recreation"},  
            new Category(){ ParentCategory = "Sports", ChildCategory = "Rugby"},  
            new Category(){ ParentCategory = "Sports", ChildCategory = "Sailing"},  
            new Category(){ ParentCategory = "Sports", ChildCategory = "Skiing"},  
            new Category(){ ParentCategory = "Sports", ChildCategory = "Soccer"},  
            new Category(){ ParentCategory = "Sports", ChildCategory = "Sporting Goods"},  
            new Category(){ ParentCategory = "Sports", ChildCategory = "Sports"},  
            new Category(){ ParentCategory = "Sports", ChildCategory = "Surfing"},  
            new Category(){ ParentCategory = "Sports", ChildCategory = "Swimming"},  
            new Category(){ ParentCategory = "Sports", ChildCategory = "Table Tennis"},  
            new Category(){ ParentCategory = "Sports", ChildCategory = "Tennis"},  
            new Category(){ ParentCategory = "Sports", ChildCategory = "Ultimate Frisbee"},  
            new Category(){ ParentCategory = "Sports", ChildCategory = "Volley Ball"},  
            new Category(){ ParentCategory = "Sustainability", ChildCategory = "Biofuel"},  
            new Category(){ ParentCategory = "Sustainability", ChildCategory = "Biomass Energy"},  
            new Category(){ ParentCategory = "Sustainability", ChildCategory = "Clean Energy"},  
            new Category(){ ParentCategory = "Sustainability", ChildCategory = "CleanTech"},  
            new Category(){ ParentCategory = "Sustainability", ChildCategory = "Energy Efficiency"},  
            new Category(){ ParentCategory = "Sustainability", ChildCategory = "Environmental Engineering"},  
            new Category(){ ParentCategory = "Sustainability", ChildCategory = "Green Building"},  
            new Category(){ ParentCategory = "Sustainability", ChildCategory = "Green Consumer Goods"},  
            new Category(){ ParentCategory = "Sustainability", ChildCategory = "GreenTech"},  
            new Category(){ ParentCategory = "Sustainability", ChildCategory = "Natural Resources"},  
            new Category(){ ParentCategory = "Sustainability", ChildCategory = "Organic"},  
            new Category(){ ParentCategory = "Sustainability", ChildCategory = "Pollution Control"},  
            new Category(){ ParentCategory = "Sustainability", ChildCategory = "Recycling"},  
            new Category(){ ParentCategory = "Sustainability", ChildCategory = "Renewable Energy"},  
            new Category(){ ParentCategory = "Sustainability", ChildCategory = "Solar"},  
            new Category(){ ParentCategory = "Sustainability", ChildCategory = "Sustainability"},  
            new Category(){ ParentCategory = "Sustainability", ChildCategory = "Waste Management"},  
            new Category(){ ParentCategory = "Sustainability", ChildCategory = "Water Purification"},  
            new Category(){ ParentCategory = "Sustainability", ChildCategory = "Wind Energy"},  
            new Category(){ ParentCategory = "Transportation", ChildCategory = "Air Transportation"},  
            new Category(){ ParentCategory = "Transportation", ChildCategory = "Automotive"},  
            new Category(){ ParentCategory = "Transportation", ChildCategory = "Autonomous Vehicles"},  
            new Category(){ ParentCategory = "Transportation", ChildCategory = "Car Sharing"},  
            new Category(){ ParentCategory = "Transportation", ChildCategory = "Courier Service"},  
            new Category(){ ParentCategory = "Transportation", ChildCategory = "Delivery Service"},  
            new Category(){ ParentCategory = "Transportation", ChildCategory = "Electric Vehicle"},  
            new Category(){ ParentCategory = "Transportation", ChildCategory = "Ferry Service"},  
            new Category(){ ParentCategory = "Transportation", ChildCategory = "Fleet Management"},  
            new Category(){ ParentCategory = "Transportation", ChildCategory = "Food Delivery"},  
            new Category(){ ParentCategory = "Transportation", ChildCategory = "Freight Service"},  
            new Category(){ ParentCategory = "Transportation", ChildCategory = "Last Mile Transportation"},  
            new Category(){ ParentCategory = "Transportation", ChildCategory = "Limousine Service"},  
            new Category(){ ParentCategory = "Transportation", ChildCategory = "Logistics"},  
            new Category(){ ParentCategory = "Transportation", ChildCategory = "Marine Transportation"},  
            new Category(){ ParentCategory = "Transportation", ChildCategory = "Parking"},  
            new Category(){ ParentCategory = "Transportation", ChildCategory = "Ports and Harbors"},  
            new Category(){ ParentCategory = "Transportation", ChildCategory = "Procurement"},  
            new Category(){ ParentCategory = "Transportation", ChildCategory = "Public Transportation"},  
            new Category(){ ParentCategory = "Transportation", ChildCategory = "Railroad"},  
            new Category(){ ParentCategory = "Transportation", ChildCategory = "Recreational Vehicles"},  
            new Category(){ ParentCategory = "Transportation", ChildCategory = "Ride Sharing"},  
            new Category(){ ParentCategory = "Transportation", ChildCategory = "Same Day Delivery"},  
            new Category(){ ParentCategory = "Transportation", ChildCategory = "Shipping"},  
            new Category(){ ParentCategory = "Transportation", ChildCategory = "Shipping Broker"},  
            new Category(){ ParentCategory = "Transportation", ChildCategory = "Space Travel"},  
            new Category(){ ParentCategory = "Transportation", ChildCategory = "Supply Chain Management"},  
            new Category(){ ParentCategory = "Transportation", ChildCategory = "Taxi Service"},  
            new Category(){ ParentCategory = "Transportation", ChildCategory = "Transportation"},  
            new Category(){ ParentCategory = "Transportation", ChildCategory = "Warehousing"},  
            new Category(){ ParentCategory = "Transportation", ChildCategory = "Water Transportation"},  
            new Category(){ ParentCategory = "Travel and Tourism", ChildCategory = "Adventure Travel"},  
            new Category(){ ParentCategory = "Travel and Tourism", ChildCategory = "Amusement Park and Arcade"},  
            new Category(){ ParentCategory = "Travel and Tourism", ChildCategory = "Business Travel"},  
            new Category(){ ParentCategory = "Travel and Tourism", ChildCategory = "Casino"},  
            new Category(){ ParentCategory = "Travel and Tourism", ChildCategory = "Hospitality"},  
            new Category(){ ParentCategory = "Travel and Tourism", ChildCategory = "Hotel"},  
            new Category(){ ParentCategory = "Travel and Tourism", ChildCategory = "Museums and Historical Sites"},  
            new Category(){ ParentCategory = "Travel and Tourism", ChildCategory = "Parks"},  
            new Category(){ ParentCategory = "Travel and Tourism", ChildCategory = "Resorts"},  
            new Category(){ ParentCategory = "Travel and Tourism", ChildCategory = "Timeshare"},  
            new Category(){ ParentCategory = "Travel and Tourism", ChildCategory = "Tour Operator"},  
            new Category(){ ParentCategory = "Travel and Tourism", ChildCategory = "Tourism"},  
            new Category(){ ParentCategory = "Travel and Tourism", ChildCategory = "Travel"},  
            new Category(){ ParentCategory = "Travel and Tourism", ChildCategory = "Travel Accommodations"},  
            new Category(){ ParentCategory = "Travel and Tourism", ChildCategory = "Travel Agency"},  
            new Category(){ ParentCategory = "Travel and Tourism", ChildCategory = "Vacation Rental"},  
            new Category(){ ParentCategory = "Video", ChildCategory = "Animation"},  
            new Category(){ ParentCategory = "Video", ChildCategory = "Broadcasting"},  
            new Category(){ ParentCategory = "Video", ChildCategory = "Film"},  
            new Category(){ ParentCategory = "Video", ChildCategory = "Film Distribution"},  
            new Category(){ ParentCategory = "Video", ChildCategory = "Film Production"},  
            new Category(){ ParentCategory = "Video", ChildCategory = "Motion Capture"},  
            new Category(){ ParentCategory = "Video", ChildCategory = "TV"},  
            new Category(){ ParentCategory = "Video", ChildCategory = "TV Production"},  
            new Category(){ ParentCategory = "Video", ChildCategory = "Video"},  
            new Category(){ ParentCategory = "Video", ChildCategory = "Video Editing"},  
            new Category(){ ParentCategory = "Video", ChildCategory = "Video on Demand"},  
            new Category(){ ParentCategory = "Video", ChildCategory = "Video Streaming"},  
        };
    }
}
